export type DrawerParamList = {
  Home: undefined;
  HydraulicSystem: undefined;
  AdvancedHydraulic: undefined;
  BucklingShaft: undefined;
  GearPump: undefined;
  PipeRodWeight: undefined;
  PneumaticCylinder: undefined;
  HydraulicMotor: undefined;
  ThreadPitch: undefined;
  PipeConverter: undefined;
  PressureConverter: undefined;
  FlowVelocity: undefined;
  Accumulator: undefined;
  About: undefined;
  Privacy: undefined;
  Terms: undefined;
  Contact: undefined;
  ReportBug: undefined;
};
